implement basic error handling

diff --git a/lfbundle-previewer b/lfbundle-previewer
--- a/lfbundle-previewer
+++ b/lfbundle-previewer
@@ -1,35 +1,41 @@
 #!/usr/bin/env bash
 
-abspath="$1"; lf_previewbox_x="$4"; lf_previewbox_y="$5"; lf_previewbox_w="$2"; lf_previewbox_h="$3"
+FILEPATH_ABS="$1"
+lf_previewbox_x="$4"
+lf_previewbox_y="$5"
+lf_previewbox_w="$2"
+lf_previewbox_h="$3"
 
 preview_image() {
-    filepath="$1"
+	filepath="$1"
 
 	chafa --animate false --view-size "${lf_previewbox_w}x${lf_previewbox_h}" "$filepath"
 }
 
-preview_archive() {
-    filepath="$1"
+preview_archive() (
+	trap "exit 1" ERR
+	set -eo pipefail
+	filepath="$1"
 
-    case "$1" in
-    *.tar|*.tar.*)
-        tar -tf "$filepath"
-        ;;
-    *.zip)
-        zipinfo -1 "$filepath"
-        ;;
-    *.7z)
-        # https://stackoverflow.com/a/68070379
-        7z l -ba "$filepath" | grep -oP '(?<=^.{53}).*'
-        ;;
-    *.rar)
-        rar lb "$filepath"
-        ;;
-    *)
-        return 1
-        ;;
-    esac | tree -L 1 -F --dirsfirst --noreport --fromfile .
-}
+	case "$1" in
+	*.tar|*.tar.*)
+		tar -tf "$filepath"
+		;;
+	*.zip)
+		zipinfo -1 "$filepath"
+		;;
+	*.7z)
+		# https://stackoverflow.com/a/68070379
+		7z l -ba "$filepath" | grep -oP '(?<=^.{53}).*'
+		;;
+	*.rar)
+		rar lb "$filepath"
+		;;
+	*)
+		return 1
+		;;
+	esac | tree -L 1 -F --dirsfirst --noreport --fromfile .
+)
 
 # # Preview "$1"'s file content as text using '-' for stdin. Use as common text
 # # preview wrapper, so that pagination will apply to text aswell. '-p' disables
@@ -46,12 +52,6 @@ preview_archive() {
 # thumbnail_abspath="$LFBUNDLE_TEMPDIR/thumbnail.png" # thumbnail path for ad-hoc conversions
 # page="$(cat "$LFBUNDLE_TEMPDIR/page")" # pagination offset
 
-# # Assign inputs to variables. The unusual order in which the coordinates are
-# # passed into this script is determined by lf. 'abspath' is the absolute path
-# # of the file to be previewed and the coordinates refer the drawing area for
-# # image previews.
-# abspath="$1"; lf_previewbox_x="$4"; lf_previewbox_y="$5"; lf_previewbox_w="$2"; lf_previewbox_h="$3"
-
 # # BUG: lf displays stdout output offset by two cells to the right with respect
 # # to the preview box's boundaries. In order to align image previews with text
 # # we add that offset to the preview coordinates.
@@ -60,49 +60,70 @@ preview_archive() {
 # Determine the number of lines required for the full filename to be displayed
 # and add that to the y-offset for image previews. Add another offset for the
 # horizontal separator line.
-filename="$(basename "$abspath")"
-# filename_wrapped="$(echo "$filename" | fold -w "$IMAGE_PREVIEWBOX_W")"
-# num_lines="$(echo "$filename_wrapped" | wc -l)"
-# IMAGE_PREVIEWBOX_Y=$((lf_previewbox_y+num_lines+1)); IMAGE_PREVIEWBOX_H=$((lf_previewbox_h-lf_previewbox_y-1))
-
-# # Print the filename and a separator line. The length of the separator line matches the
-# # length of the file name.
-# printf "\033[1;38;5;253m$filename_wrapped\033[0m\n"
-# w_sepline=$IMAGE_PREVIEWBOX_W
-# if [ "$num_lines" -eq 1 ]; then
-# 	w_sepline="$(echo "$filename_wrapped" | tail -1 | tr -d '\n' | wc -m)"
-# fi
-# printf '─%.0s' $(seq 1 $w_sepline); echo
-
 
 THUMBNAIL_ABSPATH="$LFBUNDLE_TEMPDIR/thumbnail.png" # thumbnail path for ad-hoc conversions
 
-case "$(echo "$filename" | tr '[:upper:]' '[:lower:]')" in
-*.pdf|*.ps)
-	gs -o "$THUMBNAIL_ABSPATH" -sDEVICE=pngalpha "$filename" >/dev/null
-	preview_image "$THUMBNAIL_ABSPATH"
+# TODO: line wrapping
+#       lf doesn't automatically wrap the output inside the viewbox.
+generate_preview() (
+	ERROR_PREVIEW=1
+	ERROR_NO_PREVIEWER_CONFIGURED_FOR_FILE=2
+	trap "exit $ERROR_PREVIEW" ERR
+	set -eo pipefail
+	filepath="$1"
+
+	filename="$(basename "$filepath")"
+	case "$(echo "$filename" | tr '[:upper:]' '[:lower:]')" in
+	*.pdf|*.ps)
+		gs -o "$THUMBNAIL_ABSPATH" -sDEVICE=pngalpha "$filepath" >/dev/null
+		preview_image "$THUMBNAIL_ABSPATH"
+		;;
+	*.jpg|*.jpeg|*.png|*.bmp|*.tiff|*.gif|*.svg)
+		preview_image "$filepath"
+		;;
+	*.avi|*.webm|*.webp|*.mp4|*.mkv)
+		ffmpeg -y -i "$filepath" -vframes 1 "$THUMBNAIL_ABSPATH"
+		preview_image "$THUMBNAIL_ABSPATH"
+		;;
+	*.tar|*.tar.*|*.7z|*.rar|*.zip)
+		preview_archive "$filepath"
+		;;
+	# *.iso)
+	# 	iso-info --no-header "$filepath"
+	# 	;;
+	*.drawio)
+		echo TODO
+		;;
+	*)
+		if file -b --mime-type "$filepath" | grep -q '^application\/'; then
+			return "$ERROR_NO_PREVIEWER_CONFIGURED_FOR_FILE"
+		else
+			bat --style plain --color always "$filepath"
+		fi
+		;;
+	esac
+)
+
+preview="$(generate_preview "$FILEPATH_ABS")"
+case "$?" in
+0)
+	echo "$preview"
 	;;
-*.jpg|*.jpeg|*.png|*.bmp|*.tiff|*.gif|*.svg)
-	preview_image "$abspath"
+1)
+	echo "Error generating preview, using 'file':"
+	file "$FILEPATH_ABS"
 	;;
-*.avi|*.webm|*.webp|*.mp4|*.mkv)
-	ffmpeg -y -i "$abspath" -vframes 1 "$THUMBNAIL_ABSPATH"
-	preview_image "$THUMBNAIL_ABSPATH"
-    ;;
-*.tar|*.tar.*|*.7z|*.rar|*.zip)
-    preview_archive "$abspath"
-    ;;
-*.json|*.md)
-	bat --style plain --color always "$abspath"
+2)
+	echo "No previewer configured for file, using 'file':"
+	file "$FILEPATH_ABS"
 	;;
 esac
+# if [[ "$?" == 0 ]]; then
+# 	echo "$preview"
+# else
+# 	echo "Error generating preview :("
+# fi
 
-# TODO: Generic error handler (probably using a bashism/hook)
-
-# *.avi|*.mp4|*.mkv|*.webm)
-# 	ffmpeg -y -i "$abspath" -vframes 1 "$thumbnail_abspath"
-# 	preview_image "$thumbnail_abspath"
-# 	;;
 # *.odt|*.ods|*.odp|*.odg|*.odf|*.odb|*.doc|*.docx)
 # 	echo
 # 	soffice --cat "$abspath" | preview_text -p -
@@ -113,20 +134,12 @@ esac
 # 	gm convert "$buffer" "$thumbnail_abspath"
 # 	preview_image "$thumbnail_abspath"
 # 	;;
-# *.jpg|*.jpeg|*.png|*.bmp|*.tiff|*.gif|*.svg)
-# 	preview_image "$abspath"
-# 	;;
-# *.svg)
-# 	gm convert "$abspath" "$thumbnail_abspath"
-# 	preview_image "$thumbnail_abspath"
-# 	;;
 # *.iso)
 # 	iso-info --no-header "$abspath" | tail -n +2 | preview_text -p -
-# 	;;
-# *.json)
-# 	jq '.' "$abspath"
 # 	;;
 # *) preview_text "$abspath"
 # 	;;
 # esac
+#
+
 return 127 # nonzero retcode to disable preview caching
